//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnrollmentRequest", Namespace="http://tempuri.org/")]
    public partial class EnrollmentRequest : object
    {
        
        private string NoExpedienteField;
        
        private string CicloField;
        
        private int MesInicioPagoField;
        
        private string CarreraIdField;
        
        private string InscripcionCargoIdField;
        
        private string CarneCargoIdField;
        
        private string CargoMensualIdField;
        
        private string DiaPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NoExpediente
        {
            get
            {
                return this.NoExpedienteField;
            }
            set
            {
                this.NoExpedienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ciclo
        {
            get
            {
                return this.CicloField;
            }
            set
            {
                this.CicloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int MesInicioPago
        {
            get
            {
                return this.MesInicioPagoField;
            }
            set
            {
                this.MesInicioPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CarreraId
        {
            get
            {
                return this.CarreraIdField;
            }
            set
            {
                this.CarreraIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string InscripcionCargoId
        {
            get
            {
                return this.InscripcionCargoIdField;
            }
            set
            {
                this.InscripcionCargoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CarneCargoId
        {
            get
            {
                return this.CarneCargoIdField;
            }
            set
            {
                this.CarneCargoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CargoMensualId
        {
            get
            {
                return this.CargoMensualIdField;
            }
            set
            {
                this.CargoMensualIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DiaPago
        {
            get
            {
                return this.DiaPagoField;
            }
            set
            {
                this.DiaPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnrollmentResponse", Namespace="http://tempuri.org/")]
    public partial class EnrollmentResponse : object
    {
        
        private int StatusCodeField;
        
        private string MessageField;
        
        private string CarneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Carne
        {
            get
            {
                return this.CarneField;
            }
            set
            {
                this.CarneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatementRequest", Namespace="http://tempuri.org/")]
    public partial class AccountStatementRequest : object
    {
        
        private string CarneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Carne
        {
            get
            {
                return this.CarneField;
            }
            set
            {
                this.CarneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatementResponse", Namespace="http://tempuri.org/")]
    public partial class AccountStatementResponse : object
    {
        
        private int StatusCodeField;
        
        private string MessageField;
        
        private ServiceReference.AccountStatement[] AccountStatementsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ServiceReference.AccountStatement[] AccountStatements
        {
            get
            {
                return this.AccountStatementsField;
            }
            set
            {
                this.AccountStatementsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatement", Namespace="http://tempuri.org/")]
    public partial class AccountStatement : object
    {
        
        private string CarneField;
        
        private string NombreField;
        
        private string DescripcionField;
        
        private decimal MontoField;
        
        private decimal MoraField;
        
        private decimal DescuentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Carne
        {
            get
            {
                return this.CarneField;
            }
            set
            {
                this.CarneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Mora
        {
            get
            {
                return this.MoraField;
            }
            set
            {
                this.MoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Descuento
        {
            get
            {
                return this.DescuentoField;
            }
            set
            {
                this.DescuentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspiranteRequest", Namespace="http://tempuri.org/")]
    public partial class AspiranteRequest : object
    {
        
        private string ApellidoField;
        
        private string NombreField;
        
        private string DireccionField;
        
        private string TelefonoField;
        
        private string EmailField;
        
        private string CarreraIdField;
        
        private string ExamenIdField;
        
        private string JornadaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Apellido
        {
            get
            {
                return this.ApellidoField;
            }
            set
            {
                this.ApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CarreraId
        {
            get
            {
                return this.CarreraIdField;
            }
            set
            {
                this.CarreraIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExamenId
        {
            get
            {
                return this.ExamenIdField;
            }
            set
            {
                this.ExamenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string JornadaId
        {
            get
            {
                return this.JornadaIdField;
            }
            set
            {
                this.JornadaIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AspiranteResponse", Namespace="http://tempuri.org/")]
    public partial class AspiranteResponse : object
    {
        
        private int StatusCodeField;
        
        private string MessageField;
        
        private string NoExpedienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NoExpediente
        {
            get
            {
                return this.NoExpedienteField;
            }
            set
            {
                this.NoExpedienteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IEnrollmentService")]
    public interface IEnrollmentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrollmentService/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.TestResponse> TestAsync(ServiceReference.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrollmentService/EnrollmentProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.EnrollmentProcessResponse> EnrollmentProcessAsync(ServiceReference.EnrollmentProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrollmentService/AccountStatementProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.AccountStatementProcessResponse> AccountStatementProcessAsync(ServiceReference.AccountStatementProcessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnrollmentService/CandidateRecordProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference.CandidateRecordProcessResponse> CandidateRecordProcessAsync(ServiceReference.CandidateRecordProcessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.TestRequestBody Body;
        
        public TestRequest()
        {
        }
        
        public TestRequest(ServiceReference.TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        public TestRequestBody()
        {
        }
        
        public TestRequestBody(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.TestResponseBody Body;
        
        public TestResponse()
        {
        }
        
        public TestResponse(ServiceReference.TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody()
        {
        }
        
        public TestResponseBody(string TestResult)
        {
            this.TestResult = TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnrollmentProcessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnrollmentProcess", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.EnrollmentProcessRequestBody Body;
        
        public EnrollmentProcessRequest()
        {
        }
        
        public EnrollmentProcessRequest(ServiceReference.EnrollmentProcessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnrollmentProcessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.EnrollmentRequest request;
        
        public EnrollmentProcessRequestBody()
        {
        }
        
        public EnrollmentProcessRequestBody(ServiceReference.EnrollmentRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnrollmentProcessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnrollmentProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.EnrollmentProcessResponseBody Body;
        
        public EnrollmentProcessResponse()
        {
        }
        
        public EnrollmentProcessResponse(ServiceReference.EnrollmentProcessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnrollmentProcessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.EnrollmentResponse EnrollmentProcessResult;
        
        public EnrollmentProcessResponseBody()
        {
        }
        
        public EnrollmentProcessResponseBody(ServiceReference.EnrollmentResponse EnrollmentProcessResult)
        {
            this.EnrollmentProcessResult = EnrollmentProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountStatementProcessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountStatementProcess", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.AccountStatementProcessRequestBody Body;
        
        public AccountStatementProcessRequest()
        {
        }
        
        public AccountStatementProcessRequest(ServiceReference.AccountStatementProcessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountStatementProcessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.AccountStatementRequest request;
        
        public AccountStatementProcessRequestBody()
        {
        }
        
        public AccountStatementProcessRequestBody(ServiceReference.AccountStatementRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccountStatementProcessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccountStatementProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.AccountStatementProcessResponseBody Body;
        
        public AccountStatementProcessResponse()
        {
        }
        
        public AccountStatementProcessResponse(ServiceReference.AccountStatementProcessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountStatementProcessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.AccountStatementResponse AccountStatementProcessResult;
        
        public AccountStatementProcessResponseBody()
        {
        }
        
        public AccountStatementProcessResponseBody(ServiceReference.AccountStatementResponse AccountStatementProcessResult)
        {
            this.AccountStatementProcessResult = AccountStatementProcessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CandidateRecordProcessRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CandidateRecordProcess", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.CandidateRecordProcessRequestBody Body;
        
        public CandidateRecordProcessRequest()
        {
        }
        
        public CandidateRecordProcessRequest(ServiceReference.CandidateRecordProcessRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CandidateRecordProcessRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.AspiranteRequest request;
        
        public CandidateRecordProcessRequestBody()
        {
        }
        
        public CandidateRecordProcessRequestBody(ServiceReference.AspiranteRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CandidateRecordProcessResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CandidateRecordProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference.CandidateRecordProcessResponseBody Body;
        
        public CandidateRecordProcessResponse()
        {
        }
        
        public CandidateRecordProcessResponse(ServiceReference.CandidateRecordProcessResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CandidateRecordProcessResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference.AspiranteResponse CandidateRecordProcessResult;
        
        public CandidateRecordProcessResponseBody()
        {
        }
        
        public CandidateRecordProcessResponseBody(ServiceReference.AspiranteResponse CandidateRecordProcessResult)
        {
            this.CandidateRecordProcessResult = CandidateRecordProcessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IEnrollmentServiceChannel : ServiceReference.IEnrollmentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EnrollmentServiceClient : System.ServiceModel.ClientBase<ServiceReference.IEnrollmentService>, ServiceReference.IEnrollmentService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EnrollmentServiceClient() : 
                base(EnrollmentServiceClient.GetDefaultBinding(), EnrollmentServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEnrollmentService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EnrollmentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EnrollmentServiceClient.GetBindingForEndpoint(endpointConfiguration), EnrollmentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EnrollmentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EnrollmentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EnrollmentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EnrollmentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EnrollmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.TestResponse> ServiceReference.IEnrollmentService.TestAsync(ServiceReference.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.TestResponse> TestAsync(string message)
        {
            ServiceReference.TestRequest inValue = new ServiceReference.TestRequest();
            inValue.Body = new ServiceReference.TestRequestBody();
            inValue.Body.message = message;
            return ((ServiceReference.IEnrollmentService)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.EnrollmentProcessResponse> ServiceReference.IEnrollmentService.EnrollmentProcessAsync(ServiceReference.EnrollmentProcessRequest request)
        {
            return base.Channel.EnrollmentProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.EnrollmentProcessResponse> EnrollmentProcessAsync(ServiceReference.EnrollmentRequest request)
        {
            ServiceReference.EnrollmentProcessRequest inValue = new ServiceReference.EnrollmentProcessRequest();
            inValue.Body = new ServiceReference.EnrollmentProcessRequestBody();
            inValue.Body.request = request;
            return ((ServiceReference.IEnrollmentService)(this)).EnrollmentProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.AccountStatementProcessResponse> ServiceReference.IEnrollmentService.AccountStatementProcessAsync(ServiceReference.AccountStatementProcessRequest request)
        {
            return base.Channel.AccountStatementProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.AccountStatementProcessResponse> AccountStatementProcessAsync(ServiceReference.AccountStatementRequest request)
        {
            ServiceReference.AccountStatementProcessRequest inValue = new ServiceReference.AccountStatementProcessRequest();
            inValue.Body = new ServiceReference.AccountStatementProcessRequestBody();
            inValue.Body.request = request;
            return ((ServiceReference.IEnrollmentService)(this)).AccountStatementProcessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.CandidateRecordProcessResponse> ServiceReference.IEnrollmentService.CandidateRecordProcessAsync(ServiceReference.CandidateRecordProcessRequest request)
        {
            return base.Channel.CandidateRecordProcessAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.CandidateRecordProcessResponse> CandidateRecordProcessAsync(ServiceReference.AspiranteRequest request)
        {
            ServiceReference.CandidateRecordProcessRequest inValue = new ServiceReference.CandidateRecordProcessRequest();
            inValue.Body = new ServiceReference.CandidateRecordProcessRequestBody();
            inValue.Body.request = request;
            return ((ServiceReference.IEnrollmentService)(this)).CandidateRecordProcessAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEnrollmentService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEnrollmentService_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/EnrollmentService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EnrollmentServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEnrollmentService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EnrollmentServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEnrollmentService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEnrollmentService_soap,
        }
    }
}
